routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','ContactController@index')->name('index');
Route::get('contacts/{contact}/approveDelete', 'ContactController@approveDelete')->name('contacts.approveDelete');
Route::resource('contacts', 'ContactController');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model

{
    public $timestamps = false;
    protected $fillable = ['name', 'last_name', 'number'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use App\Http\Requests\AddContact;
use App\Http\Requests\UpdateContact;
use Illuminate\Http\Request;

class ContactController extends Controller
{

    public function index()
    {
        $contacts = Contact::all();
        return view('contacts.index', compact('contacts'));
    }

    public function create()
    {
        return view('contacts.create');
    }

    public function store(AddContact $request)
    {
        Contact::updateOrCreate(
            [
                'number'=>$request->number
            ],
            [
                'name'=>$request->name,
                'last_name'=>$request->last_name
            ]);
        return redirect()->route('index');
    }

    public function edit(Contact $contact)
    {
        return view('contacts.edit', compact('contact'));
    }

    public function update(UpdateContact $request, Contact $contact)
    {
        $contact->number = $request->number;
        $contact->name = $request->name;
        $contact->last_name = $request->last_name;
        $contact->save();
        return redirect()->route('index');
    }

    public function approveDelete(Contact $contact){
        return view('contacts.delete', compact('contact'));
    }
    public function destroy(Contact $contact)
    {
        $contact_deleted = $contact->delete();
        return redirect()->route('index');
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/View/Components/EditDeleteButtons.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class EditDeleteButtons extends Component
{
    public $contact;

    /**
     * Create a new component instance.
     *
     * @param $contact
     */
    public function __construct($contact)
    {
        $this->contact = $contact;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.edit-delete-buttons');
    }
}

app/View/Components/ListItem.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class ListItem extends Component
{
    public $contact;

    /**
     * Create a new component instance.
     *
     * @param $contact
     */
    public function __construct($contact)
    {
        $this->contact = $contact;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.list-item');
    }
}

app/View/Components/Status.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class Status extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\View\View|string
     */
    public function render()
    {
        return view('components.status');
    }
}

resources/views/contacts/create.blade.php
<form id="edit-form" class="form-horizontal" method="POST" action="{{route('contacts.store')}}">
    @csrf
    <div class="card text-white bg-dark mb-0">
        <div class="card-header">
            <h2 class="m-0">Add</h2>
        </div>
        <div class="card-body">
            <!-- id -->
            <div class="form-group">
                <label class="col-form-label" for="id">Number</label>
                <input type="text" name="number" class="form-control" id="number" required>
            </div>
            <div class="form-group">
                <label class="col-form-label" for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" required autofocus>
            </div>
            <div class="form-group">
                <label class="col-form-label" for="last-name">Last Name</label>
                <input type="text" name="last_name" class="form-control" id="last_name" required autofocus>
            </div>
            <!-- /description -->
        </div>
        <input type="submit" class="btn btn-primary">
        <button type="button" id="close_modal" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    </div>
</form>

resources/views/contacts/delete.blade.php
<form id="sure-form" class="form-horizontal" method="POST" action="{{route('contacts.destroy', $contact)}}">
    @method('DELETE')
    @csrf
    <div class="card text-white bg-dark mb-0">
        <div class="card-body">
            Are you sure you want to delete this contact?
        </div>
        <input type="submit" class="btn btn-primary">
        <button type="button" id="close_modal" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    </div>
</form>

resources/views/contacts/edit.blade.php
<form id="edit-form" class="form-horizontal" method="POST" action="{{route('contacts.update', $contact->id)}}">
    @method('PUT')
    @csrf
    <div class="card text-white bg-dark mb-0">
        <div class="card-header">
            <h2 class="m-0">Edit</h2>
        </div>
        <div class="card-body">
            <!-- id -->
            <div class="form-group">
                <label class="col-form-label" for="id">Number</label>
                <input type="text" name="number" class="form-control" id="number" value="{{$contact->number}}" required>
            </div>
            <div class="form-group">
                <label class="col-form-label" for="name">Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{$contact->name}}" required autofocus>
            </div>
            <div class="form-group">
                <label class="col-form-label" for="last-name">Last Name</label>
                <input type="text" name="last_name" class="form-control" id="last_name" value="{{$contact->last_name}}" required autofocus>
            </div>
            <!-- /description -->
        </div>
        <input type="submit" class="btn btn-primary">
        <button type="button" id="close_modal" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
    </div>
</form>

resources/views/contacts/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" integrity="sha256-h20CPZ0QyXlBuAw7A+KluUYx/3pK+c7lYEpqLTlxjYQ=" crossorigin="anonymous" />
    <title>Daniel ContactBook</title>
</head>
<body>
<div class="container">

<div class="row">
        <button type="button" id="add-item" class="btn btn-primary btn-lg btn-block">ADD</button>
<div class="col-sm-12">
<ul class="list-group">
    @foreach($contacts as $contact)
        <x-list-item :contact="$contact"/>
    @endforeach
</ul>
</div>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modal-label" aria-hidden="true" style="width: 30%;height: 100%;margin: auto;margin-top: 2%">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body" id="attachment-body-content">
            </div>
        </div>
    </div>
</div>
</body>
<script
        src="https://code.jquery.com/jquery-3.5.0.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
        crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function() {
        $(document).on('click', "#add-item", function() {
            $.ajax({
                type: "GET",
                url: "{{route('contacts.create')}}",
            }).done(function(form) {
                $('#attachment-body-content').html(form);
                $('#modal').modal();
            });
        })
        $(document).on('click', "#edit-item", function() {
            var contact = $(this).parent().parent().parent().find('.contact_id').val();
            var url = '{{route('contacts.edit', ":id")}}';
            url = url.replace(':id',contact);
            $.ajax({
                type: "GET",
                url: url,
            }).done(function(form) {
                $('#attachment-body-content').html(form);
                $('#modal').modal();
            });
        })
        $(document).on('click', "#delete-item", function() {
            var contact = $(this).parent().parent().parent().find('.contact_id').val();
            var url = '{{route('contacts.approveDelete', ":id")}}';
            url = url.replace(':id',contact);
            $.ajax({
                type: "GET",
                url: url,
            }).done(function(form) {
                $('#attachment-body-content').html(form);
                $('#modal').modal();

            });
        })
    })
</script>
</html>